# docker/Dockerfile.streamlit

FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*


# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier les dépendances
COPY app_streamlit/requirements.txt /tmp/req.txt
RUN uv pip install --system --no-cache -r /tmp/req.txt

# Copier tout le contenu du dossier app_streamlit dans /app/
COPY app_streamlit/ /app/app_streamlit

ENV PYTHONPATH=/app

# Exposer le port Streamlit
EXPOSE 8501

# Commande de démarrage
CMD ["streamlit", "run", "/app/app_streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]


